swagger: '2.0'
info:
  version: 1.0.0
  title: Chat Room Application
basePath: /api
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
paths:
  /chatRooms:
    get:
      summary: Gets all the chat rooms
      operationId: getChatRooms
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ChatRoom'
  /chatRooms/{chatRoomId}/chatMessages:
    parameters:
      - name: chatRoomName
        required: true
        in: path
        description: The name of the chat room
        type: string
    get:
      summary: Gets all the chat messages for a given chat room
      operationId: getChatMessages
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ChatMessage'
    post:
      summary: Sends a new chat message to the given chat room
      operationId: postChatMessage
      parameters:
        - name: chatMessage
          required: true
          in: body
          description: The chat message
          schema:
            $ref: '#/definitions/ChatMessage'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ChatMessage'
definitions:
  ChatRoom:
    properties:
      name:
        type: string
      description:
        type: string
  ChatMessage:
    properties:
      userName:
        type: string
      content:
        type: string